import MainLayout from "@/components/layout/main";
import Head from "next/head";
import { useRouter } from "next/router";
import { NextPageWithLayout } from "../models";
import styles from "../styles/Home.module.css";

const Home: NextPageWithLayout = () => {
  const router = useRouter();
  const handleGotoDetails = () => {
    router.push({
      pathname: "posts/[postId]",
      query: {
        postId: 123,
        ref: "social",
      },
    });
  };
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h3>Home Page</h3>
      </div>
    </>
  );
};

Home.Layout = MainLayout;

export default Home;
